// Code generated by cmd/reset; DO NOT EDIT.

package model

// Reset resets all fields of Example to their zero values
func (r *Example) Reset() {
	r.ID = 0
	r.Name = ""
	r.Active = false
	r.Tags = r.Tags[:0]
	clear(r.Metadata)
	if r.Counter != nil {
		*r.Counter = 0
	}
	if r.Score != nil {
		*r.Score = 0
	}
	if resetter, ok := any(&r.Nested).(interface{ Reset() }); ok {
		resetter.Reset()
	} else {
		r.Nested = NestedStruct{}
	}
	if r.PtrNest != nil {
		if resetter, ok := any(r.PtrNest).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			*r.PtrNest = NestedStruct{}
		}
	}
}

// Reset resets all fields of ComplexExample to their zero values
func (r *ComplexExample) Reset() {
	r.ID = 0
	r.Data = r.Data[:0]
	r.Items = r.Items[:0]
	clear(r.Config)
	if r.PtrInt != nil {
		*r.PtrInt = 0
	}
	if resetter, ok := any(&r.SubStruct).(interface{ Reset() }); ok {
		resetter.Reset()
	} else {
		r.SubStruct = SubWithReset{}
	}
	if r.PtrSub != nil {
		if resetter, ok := any(r.PtrSub).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			*r.PtrSub = SubWithReset{}
		}
	}
}

// Reset resets all fields of SubWithReset to their zero values
func (r *SubWithReset) Reset() {
	r.Name = ""
	r.Count = 0
	r.Flags = r.Flags[:0]
}
