package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"

	"golang.org/x/tools/go/packages"
)

const outputFileName = "reset.gen.go"

// generateResetFile creates a reset.gen.go file containing Reset() methods
// for all structs in the given package.
func generateResetFile(pkg *packages.Package, structs []*structInfo) error {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "// Code generated by cmd/reset; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg.Name)

	for _, s := range structs {
		generateResetMethod(&buf, s)
		buf.WriteString("\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Printf("Warning: failed to format generated code: %v", err)
		formatted = buf.Bytes()
	}

	var outputPath string
	if len(pkg.GoFiles) > 0 {
		dir := filepath.Dir(pkg.GoFiles[0])
		outputPath = filepath.Join(dir, outputFileName)
	} else if len(pkg.CompiledGoFiles) > 0 {
		dir := filepath.Dir(pkg.CompiledGoFiles[0])
		outputPath = filepath.Join(dir, outputFileName)
	} else {
		return fmt.Errorf("no files in package %s", pkg.PkgPath)
	}

	if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
		return fmt.Errorf("failed to write file %s: %w", outputPath, err)
	}

	log.Printf("Generated %s for package %s", outputPath, pkg.Name)
	return nil
}

// generateResetMethod generates a Reset() method for a single struct.
func generateResetMethod(buf *bytes.Buffer, s *structInfo) {
	fmt.Fprintf(buf, "// Reset resets all fields of %s to their zero values\n", s.Name)
	fmt.Fprintf(buf, "func (r *%s) Reset() {\n", s.Name)

	for _, field := range s.Fields {
		generateFieldReset(buf, field)
	}

	fmt.Fprintf(buf, "}")
}

// generateFieldReset generates the reset code for a single field.
func generateFieldReset(buf *bytes.Buffer, field *fieldInfo) {
	fieldRef := fmt.Sprintf("r.%s", field.Name)

	switch {
	case field.IsSlice:
		fmt.Fprintf(buf, "\t%s = %s[:0]\n", fieldRef, fieldRef)

	case field.IsMap:
		fmt.Fprintf(buf, "\tclear(%s)\n", fieldRef)

	case field.IsPtr:
		if field.IsStruct {
			fmt.Fprintf(buf, "\tif %s != nil {\n", fieldRef)
			fmt.Fprintf(buf, "\t\tif resetter, ok := any(%s).(interface{ Reset() }); ok {\n", fieldRef)
			fmt.Fprintf(buf, "\t\t\tresetter.Reset()\n")
			fmt.Fprintf(buf, "\t\t} else {\n")
			fmt.Fprintf(buf, "\t\t\t*%s = %s{}\n", fieldRef, getBaseTypeName(field.ElemType))
			fmt.Fprintf(buf, "\t\t}\n")
			fmt.Fprintf(buf, "\t}\n")
		} else {
			fmt.Fprintf(buf, "\tif %s != nil {\n", fieldRef)
			zeroValue := getZeroValue(field.ElemType)
			fmt.Fprintf(buf, "\t\t*%s = %s\n", fieldRef, zeroValue)
			fmt.Fprintf(buf, "\t}\n")
		}

	case field.IsStruct:
		fmt.Fprintf(buf, "\tif resetter, ok := any(&%s).(interface{ Reset() }); ok {\n", fieldRef)
		fmt.Fprintf(buf, "\t\tresetter.Reset()\n")
		fmt.Fprintf(buf, "\t} else {\n")
		fmt.Fprintf(buf, "\t\t%s = %s{}\n", fieldRef, field.TypeExpr)
		fmt.Fprintf(buf, "\t}\n")

	default:
		zeroValue := getZeroValue(field.TypeExpr)
		fmt.Fprintf(buf, "\t%s = %s\n", fieldRef, zeroValue)
	}
}
